# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Project Reciprocity' do

end

target 'Project ReciprocityTests' do

end

target 'Project ReciprocityUITests' do

end

